### ISSUE TITLE
 has no exported member 'JPA_API_URL'

### ISSUE THREAD

**Issue by Genya9000** [pvchk/spring-angular#35]
1. go to the package frontend/todo
2. run app like ' ng serve'
3. expected result : the app should working on port 4200
4. actual result: 'ERROR in src/app/service/data/todo-data.service.ts:4:18 - error TS2305: Module'"../../app.constants"' has no exported member 'JPA_API_URL'.'
5. Severity: blocking
![Снимок экрана от 2020-01-12 21-03-53](https://user-images.githubusercontent.com/38878887/72224088-10f79080-357f-11ea-92a3-b5ef711d9108.png)

**Comment by Genya9000** [comment]
What do you think about this bug?

**Comment by pyavchik** [comment]
Resolved.
Could you recheck pls?

**Comment by evgeny-haliman** [comment]
All work!!! Congrats
